export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, minHeight: '100vh', overflowX: 'hidden' }}>
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            minHeight: '100vh',
          }}
        >
          <main style={{ flex: 1 }}>{children}</main>

          <footer
            style={{
              fontFamily: `Inter, -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif`,
              textAlign: 'center',
              padding: '10px',
              background: '#111',
              color: '#fff',
              fontSize: '14px',
            }}
          >
            © 2025 PetSystem. Todos os direitos reservados.
          </footer>
        </div>
      </body>
    </html>
  )
}
